### ISSUE TITLE
error making complex predefined shapes

### ISSUE THREAD

**Issue by DreadKnight** [Embroidermodder/Embroidermodder#115]
I'm new to embroidery software (linux user). One of the first things after compiling I've tried making a heart shape and received this error:

>The rubber object added contains no points. The command that created this object has flawed logic. The object will be deleted.

Snowflake and dolphin shapes are also problematic.

**Comment by tatarize** [comment]
I'm pretty sure the logic behind those shape commands were not completed before the project more or less became stagnant, for now, if you want something that works inkstitch ( https://github.com/inkstitch/inkstitch ) can sort of do some work.  And I'm kind of slowly adding some embroidermodder ideas into my own embroidepy project ( https://github.com/EmbroidePy/EmbroidePy ). But, I am seriously considering going the other way too.

Putting aside several faults, inkstitch's use of Eulerian Fills is actually a bit novel and does make filling in that missing logic much more reasonable. Most of the time a lot of the commands were setup and interfaced nicely but the logic behind those commands is a bit complex and got pushed. With Eulerian fills you can reasonably do an okay job filling *any* complex set of shapes with rather basic geometric logic. Basically you find the intersections between a shape-area-polygon-bezigon, etc and a Eulerian fill then add some scaffolding to the edges to ensure a wholly Eulerian graph and simply solve a Eulerian path within that that minimizes the scaffolding use, or somet other relevant criteria.

At some point I'm going to have to deep dive into the Embrodermodder code to find out what sorts of hooks a generalized fill operation would need to use, to quickly patch the missing bits of code. 

See #79 and #94. The Eulerian fill algorithm would at least make filling complex predefined (or any defined shapes) reasonably easy to do. Which actually serves to pretty reasonably reduce the geometric requirements for the required algorithms. You really can take even the most complex shapes with holes or extremely complex fill patterns and reduce it cookie-cutting the background fill with a foreground shape, and scaffolding the edges, and solving the travelling-salesman-problem with some good approximation like 2-opt.

**Comment by tatarize** [comment]
Guess I'm wrong, even the other bits don't have any fill algorithms it seems like they really are just sort of created and then go away. None of it seems like it has a place to even put a fill algorithm.

**Comment by DreadKnight** [comment]
@tatarize Thanks for the prompt reply, will keep an eye on your project :+1: 

So regarding this issue, it's a duplicate of the old #79 - should have did some searching...

**Comment by Metallicow** [comment]
Just do not forget to add rubber.

**Comment by Metallicow** [comment]
@DreadKnight @tatarize 
This is a start. That ought to keep you occupied.
https://en.wikipedia.org/wiki/King_James_Version

**Comment by Metallicow** [comment]
@DreadKnight Read this. Then look at the code. This might help. https://github.com/norvig/pytudes/blob/master/ipynb/TSP.ipynb
