### ISSUE TITLE
Conflict in .gitignore since a couple of days

### ISSUE THREAD

**Issue by DivingDuck** [Embroidermodder/Embroidermodder#119]
I like to report an conflict error with .gitignore. Happen since last update 4 days ago. It prevent to update local repositories.

The error is the new line 59: .qmake.stash 
[Source is .gitignore 59d880d (Skylar Ittner) vs .gitignore 275eb4f (Josh Varga)]

**Comment by robin-swift** [comment]
fixed, we don't use qmake anyway
