### ISSUE TITLE
Is there prebuilt binaries for windows anywhere?

### ISSUE THREAD

**Issue by joebywan** [Embroidermodder/Embroidermodder#120]
Came across the project, saw it was windows/linux/mac, just can't find a windows download.  Anyone able to point me in the right direction please?

**Comment by bgiesbrecht** [comment]
http://embroidermodder.org/downloads.html

**Comment by joebywan** [comment]
The site says it's a 6yr old binary, that's why I was looking on github for
something more up to date.

**Comment by JoshVarga** [comment]
There is also a nightly build right now only for windows 32bit mode but
should work.

Here: https://github.com/Embroidermodder/nightly-ci
