### ISSUE TITLE
Not an issue but a question. Is there a way programmably to get the width and height of a dst

### ISSUE THREAD

**Issue by Asimov500** [Embroidermodder/Embroidermodder#121]
I am taking multiple DSTs and creating a bigger DST from the DSTs. I know I can read the header of the DST, but sometimes the header information is incorrect if somebody has manually edited a DST.
Is there a way to get the width and height of the DST without reading the header?

I know this is possible because the Wilcom software does not read the header to get the width of a DST. I scambled a header on purpose and Wilcom can still read the DST correctly.

I didn't want to mark this as an issue but it was the only way to ask my question.

**Comment by tatarize** [comment]
Literally no software seems to actually use that. It's not worth it or safe or reasonable to care. Just load the stitches and recalculate the information.

If you want to actually just get the height and width from multiple different files pyembroidery has a command-line-interface that'll spit that information out for you. I'm unaware of other software that does such a thing. 

https://github.com/EmbroidePy/pyembroidery-CLI

It's an interface for pyembroidery which is, in turn, based a bit on libembroidery that spun off this project.

**Comment by tatarize** [comment]
Though that said specifically in embroidermodder:

boundingRect = embPattern_calcBoundingBox(pattern);

Should calculate the bounding box of the pattern for you. This is what is saved when dsts are saved. It always recalculates that.

**Comment by Asimov500** [comment]
I have written a program like the Wilcom api which takes multiple DSTs and combines them into one DST by coordinates and offsets. It works but because the coordinates being sent are the leftmost point my DSTs end up too close together. So I need to get the actuall width and height of the DST so that I can offset the coordinates being sent in.

Can you tell me how to calculate the width and height. I know I can count the stitches, eg normal an jump etc, but don't know how to get the width and height from this information?

Just read your post. How do I get the embPattern_calc. Say I have loop though all the binary data and I have 3000 stitches. I cannot see how I can get the empattern_calc from that?

Sorry if I seem a bit dim.

**Comment by tatarize** [comment]
Oh, yeah, if you're coding this up. You need a function that will calculating the extremes. This either means looping over 3000 stitches (it's not a giant operation it's n time complexity) or you can constantly track the location of all the points which will add a little overhead to all your accessors but make it a constant time operation to do.

The fact is you can't actually read those coords and expect they are correct. You can iterate over all the points and find min_x, min_y, max_x, max_y really quickly. Especially given you only need that information one time at saving.

You also need to, as you iterate over the stitches track your current position but that's pretty easily.

**Comment by tatarize** [comment]
For example pyembroidery if you take a couple dsts and merge them you'd recalculate the bounding box by calling .bounds on the pattern object the code for that:

```
def bounds(self):
        """Returns the bounds of the stitch data:
        min_x, min_y, max_x, max_y"""
        min_x = float('inf')
        min_y = float('inf')
        max_x = -float('inf')
        max_y = -float('inf')

        for stitch in self.stitches:
            if stitch[0] > max_x:
                max_x = stitch[0]
            if stitch[0] < min_x:
                min_x = stitch[0]
            if stitch[1] > max_y:
                max_y = stitch[1]
            if stitch[1] < min_y:
                min_y = stitch[1]
        return min_x, min_y, max_x, max_y
```

https://github.com/EmbroidePy/pyembroidery/blob/master/pyembroidery/EmbPattern.py starting line 221. Which is actually about exactly what you'd need to do in your program.

**Comment by Asimov500** [comment]
Hi tatarize,
I think I understand your code, but I tried something similar. I will post some code from an older version of my program. I won't post the whole lot but just the loop so you can see what I am doing.

```
fileIn.seekg(512, ios::beg);//512
char a,b,c;
int b0,b1,b2;
char bb;
int xStoreMax=0;
while (!fileIn.eof())
{
	fileIn.read(&a, 1);
	fileIn.read(&b, 1);
	fileIn.read(&c, 1);

    x = decode.decode_record_dx (a,b,c);
    y = decode.decode_record_dy (a,b,c);

    if((xStoreMax+x)>xStoreMax) xStoreMax+= x;//Relavant line
}
cout << "Max: " << xStoreMax <<  endl;
```

Here is the file header
```
LA:turtle class12  
ST:   1079
CO:  7
+X:  364
-X:  348
+Y:  288
-Y:  278
AX:+   17
AY:+    9
MX:+    0
MY:+    0
PD:******
```

However when I run the code above I get 15001 which I know is in DST scale.
To get that into mm which is what the header is I have to times by 0.1,
but it is nowhere near the correct size. I very probably doing something wrong.

**Comment by Asimov500** [comment]
I have found out how to get the plusXExtends and plusYExtends by adding these lines to the above code
```
 x2+=dx;	
y2+=dy;
if(xStoreMax<=x2) xStoreMax = x2;
if(yStoreMax<=y2) yStoreMax = y2;
```
I am having trouble getting the minimum values though of minusXExtends and minusYExtends. So far everything I have tried has failed.

**Comment by tatarize** [comment]
You do the same thing with Max but flip the signs.

`if (xStoreMin > x2) xStoreMin = x2`
`if (yStoreMin > y2) yStoreMin = y2`

You can do less or equals too but there's little point in assigning a value to itself when it's equal to itself. Also for consistency the value you are reading from the decode of the dst is dx and dy. These are the change in x and y. And the value you are keeping the running count with is typically called x and y.

**Comment by tatarize** [comment]
```
fileIn.seekg(512, ios::beg);//512
char a,b,c;
int b0,b1,b2;
char bb;
int x_min = 0, y_min=0, x_max =0, y_max=0;
while (!fileIn.eof())
{
	fileIn.read(&a, 1);
	fileIn.read(&b, 1);
	fileIn.read(&c, 1);

    dx = decode.decode_record_dx (a,b,c);
    dy = decode.decode_record_dy (a,b,c);
    x += dx;
    y += dy;
    if (x > max_x) x = max_x;
    if (y > max_y) y = max_y;   
    if (x < min_x) x = min_x;
    if (y < min_y) y = min_y;
}
```

**Comment by Asimov500** [comment]
Hi tatarize,
Thanks for all your help. My solution is very close to yours, but I wouldn't have got there without you.
```
int xStoreMax=0,xStoreMin=0,yStoreMax=0,yStoreMin = 0;

		int dx,dy;
		while (!fileIn.eof())
		{
			fileIn.read(&a, 1);
			fileIn.read(&b, 1);
			fileIn.read(&c, 1);
			b0 = (int) (unsigned char) a;
			b1 = (int) (unsigned char) b;
			b2 = (int) (unsigned char) c;
            dx = decode.decode_record_dx (a,b,c);
            dy = decode.decode_record_dy (a,b,c);
           x+=dx;
           y+=dy;
            if(xStoreMax<x) xStoreMax = x;
            if(xStoreMin>x) xStoreMin = x;
            if(yStoreMax<y) yStoreMax = y;
            if(yStoreMin>y) yStoreMin = y;
            int st= decode.decode_record_flags(c);
		 cout << "Max: " << xStoreMax <<  endl;
		 cout << "Min: " << xStoreMin <<  endl;
		 cout << "Max: " << yStoreMax <<  endl;
		 cout << "Min: " << yStoreMin <<  endl;
```
Might change these variable names next to eg minusXExtends which makes more sense.
Strangely enough I have tried this with one dst and it is spot on, and yet other dsts give me varying results. I think some of the dsts have been dabbled with. 

Strange thing is that when I load in some DSTs into Wilcom truesizer and then export them, the XExtends and the YExtends change dramatically as well. Also the export from truesizer changes the AX and AY too which is the offset.

So far I have written a program in C++ to convert a DST to an SVG, and I have written a php program to combine multiple DSTs into one DST for the web. However I was trusting the header information in the file, and I didn't want to do that.

Strangely enough when I count the colour stitches in my dst I get 1082, but in wilcom truesizer it gives 1080, so I still got a few things to work out.

Thanks for the help. I will close this in a couple of days as this was never really an issue, just needed help. Will leave it open for a few comments first.

**Comment by tatarize** [comment]
A lot of this stuff parallels some of the work done in Pyembroidery so feel free to check some of that stuff for comparison and format information. It's all MIT licensed so you can use whatever. But, it's written with the intent to be highly readable. Sort of like my pages on edutech wiki, it's all intended to make this stuff more accessible. Or ask me anything you'd want through *my username at gmail.com*, I do have a lot of expertise in this stuff.

Truesizer will sometimes automatically drop stitches that are basically trash. Like if you make stitches less than 0.2 mm it just throws those out.

**Comment by Asimov500** [comment]
Thanks tatarize. I have now also worked out how to get the AX and AY values now by reading the first jump or normal stitch and then reading the last jump or normal stitch and computing the offset. I will close this now. Thanks for the help.
