### ISSUE TITLE
Download links seem to be broken for Windows

### ISSUE THREAD

**Issue by GMaiolo** [Embroidermodder/Embroidermodder#124]
Example: http://sourceforge.net/projects/embroidermodder/files/OldFiles/embroidermodder160_exe.zip/download

Redirects to: https://sourceforge.net/directory/graphics/graphics/graphics-editors/vector/os:windows/

**Comment by larryebaum** [comment]
Still broken. Was hoping to locate a binary to simply perform conversion of vector or bimap art to vcs format. If anyone has tips/suggestions (or can do the conversion for me) much appreciated.

**Comment by SemihGuner** [comment]
Hello. I am having the same problem. The link that was provided in issue 120 no longer works. Github throws a 404.

**Comment by robin-swift** [comment]
Hi @SemihGuner 

Sorry, the original downloads are now dead. We're planning to have version 2 out by the Summer of this year (2022), which will include all downloads. Before then the software is in a broken (alpha) state.

However, if that's too long to wait, by the end of January I'm planning to release `libembroidery 1.0` (which contains all the core functions you may need) for all major operating systems. So if what you want to do is achievable with the `embroider` utility then this should solve your problem.

What is it you want to do with our software, exactly?

Cheers,
Robin (Core Developer)

**Comment by larryebaum** [comment]
Hi Robin, Happy New Year!

I’ve a logo that I wanted to convert to use on my wife’s embroidery sewing machine (pfaff I believe). It’s pretty simple 2 color logo.

Glad to send you a copy and perhaps you can tell me if it’d work with the utility?

Larry

**Comment by robin-swift** [comment]
Hi Larry,

What format is the image in? It's likely the output format should be one of:

* Tajima Embroidery Format (.dst)
* Pfaff Embroidery Format (.pcd)
* Pfaff Embroidery Format (.pcm)
* Pfaff Embroidery Format (.pcq)
* Pfaff Embroidery Format (.pcs)

If you check your machine's manual then we know what we're going from and to.

Should it require any changes to our code I'll say.

Cheers,

Robin

**Comment by larryebaum** [comment]
It’s a Pfaff 7570 and used a .pcs format best I can tell. 
I’m planning to put this onto a shirt. 

https://images.app.goo.gl/9widdEpjKzgAWY3G8

Larry

**Comment by SemihGuner** [comment]
> Hi @SemihGuner
> 
> Sorry, the original downloads are now dead. We're planning to have version 2 out by the Summer of this year (2022), which will include all downloads. Before then the software is in a broken (alpha) state.
> 
> However, if that's too long to wait, by the end of January I'm planning to release `libembroidery 1.0` (which contains all the core functions you may need) for all major operating systems. So if what you want to do is achievable with the `embroider` utility then this should solve your problem.
> 
> What is it you want to do with our software, exactly?
> 
> Cheers, Robin (Core Developer)

Hello Robin, happy new year!

I found your software while looking for a free software that I can draw embroidery pieces on. I ended up using Inkscape and https://inkstitch.org/ add-on. I am looking forward to also try your application.

Cheers, Semih

**Comment by tatarize** [comment]
[lacework.zip](https://github.com/Embroidermodder/Embroidermodder/files/7808693/lacework.zip)


![lacework2](https://user-images.githubusercontent.com/3302478/148085297-c0058893-6818-4124-bc2b-0e4061164958.png)

I did manage to auto digitize that. Well, somewhat auto.

`vpype iread -c #00AEEF -d 50 download.png iread -c gray -d 50 download.png linemerge efill -d 0.3 ewrite lacework.pes`

That's with vpype, vpype-vectrace, and vpype-embroidery.  Also it seems like the original trace is still there and didn't filter out the original traces so it has two outline layers and then two fill layers.

**Comment by larryebaum** [comment]
THANKYOU!

**Comment by robin-swift** [comment]
The initial problem of not having a build available by clicking through from the website has been fixed.
