### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Ben64** [Embroidermodder/Embroidermodder#136]
Following the steps to build I get an error, it seems that the application requires QT6 to build, but doesn't say so in the instructions?

`Project ERROR: Unknown module(s) in QT: openglwidgets`

How can I get this built for Windows, and possibly Linux? I'd donate to the project if I can get this working.

**Comment by tatarize** [comment]
I compiled it once a year or two back, it is notably not easy to do. I had to install all of qt and hack at it for while. I mostly needed to gauge the progress and the feature set it was going to have. There has been a bit of activity lately but it's hasn't had any major progress in years. The latest progress seems to be towards keeping it able to compile.

**Comment by JoshVarga** [comment]
I am able to build on Debian, I'll put together the steps.

**Comment by JoshVarga** [comment]
Here is the cmake command that works for me... I have replaced my username with USER

cmake -DCMAKE_PREFIX_PATH=/home/USER/Qt/6.1.2/gcc_64/lib/cmake -DCMAKE_PREFIX_PATH:STRING=/home/USER/Qt/6.1.2/gcc_64 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ .

**Comment by Ben64** [comment]
Great, I'll try this tonight. Did you do anything special to get the environment setup?

**Comment by davieboy01** [comment]
same problems here, tried ubuntu 16.04/18.04/20.04 debian 9 and 10 all with same problems relating to openglwidgets- was looking for a distro old enough that the default packages would just work but no joy.

@JoshVarga the Qt dir in your command, where did you download that from? or was that put there after some sort of Qt install?

**Comment by TruGolfJV** [comment]
We recently moved to Qt 6, what version are you using?

**Comment by davieboy01** [comment]
Just the default from the apt install method on the readme

**Comment by Ben64** [comment]
> @Ben64 Is it building for you now? I'm squashing other bugs right now, so if I get a yes then we can close this one.

getting undefined references to `isArcClockwise` and `getArcCenter`

**Comment by robin-swift** [comment]
Can you paste the output of (in Bash)

    find . -maxdepth 2 -mindepth 1 | grep "\.c" -

or (in PowerShell)

    PS> gci -Path "C:\Users\"  -Recurse | where {$_.Name -like '*.c'}

run in your source directory so I can see how it looks currently?

**Comment by Ben64** [comment]
from bash

```
./help/common.css
./libembroidery/embroider-main.c
./libembroidery/format-100.c
./libembroidery/format-10o.c
./libembroidery/format-art.c
./libembroidery/format-bmc.c
./libembroidery/format-bro.c
./libembroidery/format-cnd.c
./libembroidery/format-col.c
./libembroidery/format-csd.c
./libembroidery/format-csv.c
./libembroidery/format-dat.c
./libembroidery/format-dem.c
./libembroidery/format-dsb.c
./libembroidery/format-dst.c
./libembroidery/format-dsz.c
./libembroidery/format-dxf.c
./libembroidery/format-edr.c
./libembroidery/format-emd.c
./libembroidery/format-exp.c
./libembroidery/format-exy.c
./libembroidery/format-eys.c
./libembroidery/format-fxy.c
./libembroidery/format-gc.c
./libembroidery/format-gnc.c
./libembroidery/format-gt.c
./libembroidery/format-hus.c
./libembroidery/format-inb.c
./libembroidery/format-inf.c
./libembroidery/format-jef.c
./libembroidery/format-ksm.c
./libembroidery/format-max.c
./libembroidery/format-mit.c
./libembroidery/format-new.c
./libembroidery/format-ofm.c
./libembroidery/format-pcd.c
./libembroidery/format-pcm.c
./libembroidery/format-pcq.c
./libembroidery/format-pcs.c
./libembroidery/format-pec.c
./libembroidery/format-pel.c
./libembroidery/format-pem.c
./libembroidery/format-pes.c
./libembroidery/format-phb.c
./libembroidery/format-phc.c
./libembroidery/format-plt.c
./libembroidery/format-rgb.c
./libembroidery/format-sew.c
./libembroidery/format-shv.c
./libembroidery/format-sst.c
./libembroidery/format-stx.c
./libembroidery/format-svg.c
./libembroidery/format-t01.c
./libembroidery/format-t09.c
./libembroidery/format-tap.c
./libembroidery/format-thr.c
./libembroidery/format-txt.c
./libembroidery/format-u00.c
./libembroidery/format-u01.c
./libembroidery/format-vip.c
./libembroidery/format-vp3.c
./libembroidery/format-xxx.c
./libembroidery/format-zsk.c
./libembroidery/libembroidery.c
./libembroidery/thread-color.c
./samples/spiral4.csv
./samples/spiral5.csv
./samples/spiral6.csv
./samples/spiralgrid.csv
./src/application.cpp
./src/cmdprompt.cpp
./src/embdetails-dialog.cpp
./src/imagewidget.cpp
./src/layer-manager.cpp
./src/main.cpp
./src/mainwindow-actions.cpp
./src/mainwindow-commands.cpp
./src/mainwindow-menus.cpp
./src/mainwindow-settings.cpp
./src/mainwindow-toolbars.cpp
./src/mainwindow.cpp
./src/mdiarea.cpp
./src/mdiwindow.cpp
./src/native-javascript-include.cpp
./src/native-javascript-init.cpp
./src/native-javascript.cpp
./src/native-scripting.cpp
./src/object-arc.cpp
./src/object-base.cpp
./src/object-circle.cpp
./src/object-dimleader.cpp
./src/object-ellipse.cpp
./src/object-image.cpp
./src/object-line.cpp
./src/object-path.cpp
./src/object-point.cpp
./src/object-polygon.cpp
./src/object-polyline.cpp
./src/object-rect.cpp
./src/object-save.cpp
./src/object-textsingle.cpp
./src/preview-dialog.cpp
./src/property-editor.cpp
./src/selectbox.cpp
./src/settings-dialog.cpp
./src/statusbar-button.cpp
./src/statusbar.cpp
./src/undo-commands.cpp
./src/undo-editor.cpp
./src/view.cpp
./test-designs/Star.cem
./test-designs/Star.cem.eox
./thumbnailer-kde4/libembroidery-thumbnailer-kde4.cpp
```

**Comment by robin-swift** [comment]
I can't promise you a quick fix here, given the set of files you've got it seems like it should be in `libembroidery.c`.

I'm going to build a new frontend that doesn't rely on Qt but gives a similar user experience, which is likely going to take a lot of work. (Reasoning for this in #143.) So my advice is to remove your `Embroidermodder` folder and run `build.bat` in a new version when the Actions tab shows that the build passes (i.e. the tick symbol should appear on the commits). I'll leave this open until we get those passes in the GitHub Actions.

**Comment by robin-swift** [comment]
This is now resolved as the only Qt library that is compiled against is Qt5Widgets. I'm closing it, but watch #143 for developments on this front.

It would help if @Ben64 attempts to build again, if he has build issues we'll open a new issue about them.
