### ISSUE TITLE
Build issues on Linux Mint

### ISSUE THREAD

**Issue by GroundsKeeperWullie** [Embroidermodder/Embroidermodder#141]
Hello, I'm after some help with a Linux mint install please.

I've tried installing and got an issue with the following lines in view.cpp:

QRandomGenerator generator = QRandomGenerator((qint32)QDateTime::currentMSecsSinceEpoch());
sceneGripPoint = QPointF(generator.generateDouble() *1000, generator.generateDouble()*1000);

So I changed to the following to just give it some fixed values:

//QRandomGenerator generator = QRandomGenerator((qint32)QDateTime::currentMSecsSinceEpoch());
//sceneGripPoint = QPointF(generator.generateDouble() *1000, generator.generateDouble()*1000);
    sceneGripPoint = QPointF(0.5*1000, 0.6*1000);

This seemed to allow the install to proceed, however when running cmake -install, I've only got the following lines back:

~/Embroidermodder/build$ sudo cmake -install .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mrs/Embroidermodder/build

I'm not familiar with cmake, but I was expecting icons in the start menu to then open Embroidermodder after running cmake install.  Any help in getting Embroidermodder running from here much appreciated.

Kind regards,

Chris

**Comment by robin-swift** [comment]
This isn't relevant for the new front end, so I'm closing. I hope you try again sometime with the new Python/Tk interface when it's ready.
