### ISSUE TITLE
Switch to FreeGLUT 3

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/Embroidermodder#143]
Due to the many versions of Qt with massive changes in API between minor versions, its large footprint when compiled in full (several Gb, someone on here reported 39Gb I think) and linking complications due to the many modules

[See this article](http://web.archive.org/web/20161222125623/http://www.formortals.com/build-qt-static-small-microsoft-intel-gcc-compiler/) for advice on how.

I thought the best approach would be our own fork of [qtbase](https://github.com/qt/qtbase) which is cut down to just the parts we use and compiles to a single static (qt5_custom.a) library that we then compile directly into our executable.

Then, rather than the dependencies being:

    sudo apt-get install git build-essential cmake libgl1-mesa-dev \
        qtbase5-dev qtdeclarative5-dev valgrind \
        libqt5widgets5 libqt5opengl5-dev libqt5qml5 libqt5printsupport5

they'd be:

    sudo apt-get install git build-essential cmake libgl1-mesa-dev valgrind

### Issue the first.

Here's the sloccount output for `qtbase`:

    Totals grouped by language (dominant language first):
    cpp:        2193809 (78.31%)
    ansic:       460009 (16.42%)
    xml:         117563 (4.20%)
    python:       10513 (0.38%)
    java:          7491 (0.27%)
    asm:           4023 (0.14%)
    perl:          2044 (0.07%)
    sh:            1982 (0.07%)
    yacc:          1687 (0.06%)
    lex:           1333 (0.05%)
    javascript:       883 (0.03%)
    objc:            70 (0.00%)

Which is well, a lot of code to sift through, even though it's only the core of the Qt library. 

### Issue the second

    du -h qtbase
    [... lots of files ...]
    928M	qbase/

which is larger than the GH free repository maximum of 500Mb (I think). So the cut down needs to be done _before_ uploading the fork... but the history would send us over still!

### A Pragmatic Solution

A short term way of dealing with this is not relying on more of the library than is helpful. By reducing the degree of object orientation in the design we can replace Qt function calls with our own.

A long term solution would be an OpenGL custom code that acts as the gui core within `src/` that has the job of being like Qt but in under 20k SLOC as it only supports what we use. Then we can:

  1. support older systems,
  2. the embedded, library and GUI code can be more similar,
  3. we aren't as tied to C++ style which isn't my specialism and I'm an owner.

I know that this is how [Blender](https://github.com/blender/blender) does it, their external dependencies are part of the source tree and they don't rely on others for the actual GUI elements (which for a project as complex as Blender's is probably for flexibility).

### Conclusion

Start a new gui.c file with features that are system dependant but not reliant on Qt, like what the separator in the file system is, or getting information about the number of monitors with the eventual aim of simplifying dependencies.

**Comment by robin-swift** [comment]
The more current version of something more bare bones line GLUT would be GLFW which is a lot easier to build as part of the source, we'd put it in an `extern/`. The sloccount output is:

    Totals grouped by language (dominant language first):
    ansic:        65907 (96.72%)
    objc:          2173 (3.19%)
    xml:             63 (0.09%)

and it carries the same license as us, so there's no issues there for including directly into the source code.

**Comment by TruGolfJV** [comment]
That sounds great, it does sound like a lot of work though.

**Comment by JoshVarga** [comment]
That sounds great, it does sound like a lot of work though.

**Comment by robin-swift** [comment]
I'm trying it as a separate binary `embroidermodder_glfw` so no work is lost until we have an assurance that it would function at least as well.

**Comment by robin-swift** [comment]
@JoshVarga I'll also set this as a low priority, first incorporating libraries to do similar work to Qt can be done without the split.

4 libraries in `extern/` are zlib-style licensed, but I'm not sure if we can compile `freetype` in directly (I think it's viral licensed) and I don't know what alternative there is for rendering OTF/TTF fonts. Also we may need `HarfBuzz` for rendering since it's a prereq of `freetype`. So I won't use OTF/TTF fonts until then, we can just use bitmap font rendering until we have to cross that bridge.

**Comment by robin-swift** [comment]
Do you know what the policy is for linking permissive licensed software against GPL2 .so/.dlls?

**Comment by JoshVarga** [comment]
I don't know, I think that is something we'll have to look into.

**Comment by robin-swift** [comment]
Ok, so I'm switching the plan to SDL2: because it's got better support in terms of articles written about it and libraries written to interface with it (including libsdl2_ttf that would cover the text rendering). See `extern/`.

The current progress on this is that I'm moving as much of `embroidermodder.h` into `embroidermodder_c_api.h` as can easily be done. Also the code in `gui.c` acts as replacements for individual parts of Qt.

The directory management is now in `gui.c` for example.

**Comment by robin-swift** [comment]
A metric for progress on this is the C++/C sloccount ratio because none of the C code calls Qt.

**Comment by robin-swift** [comment]
Since SDL2 doesn't support GUI widgets like toolbars and menubars out of the box I'm just using the bare minimum for abstracting out what machine we're on with FreeGLUT 3 (I have more experience with this library).

The main work at the moment is removing code-data interdependency and de-object orienting for C. This is shows in `action_list` and I'm working on a new C `widget` system. As before, I'm not removing the dreaded Qt until a functional alternative is in place, this means the GH Action will fail to build the artifacts until we get there.

Pretty soon the entire project, including non-standard dependencies (i.e. not including the C stdlib, OpenGL, X11 or windows.h) will be under 100 kSLOC which is small enough for us to interrogate every backtrace to those basic system calls.

```
SLOC	Directory	SLOC-by-Language (Sorted)
61436   extern          ansic=57223,ruby=3083,cpp=847,python=220,xml=45,
                        sh=18
32336   libembroidery   ansic=17055,asm=15166,sh=115
18911   src_top_dir     cpp=12888,ansic=6023
1242    MobileViewer    xml=1122,sh=120
165     thumbnailer-kde4 cpp=105,xml=60

[... cutting the code light directories ...]

Totals grouped by language (dominant language first):
ansic:        80301 (70.22%)
asm:          15166 (13.26%)
cpp:          13840 (12.10%)
ruby:          3083 (2.70%)
xml:           1283 (1.12%)
sh:             410 (0.36%)
python:         220 (0.19%)
modula3:         56 (0.05%)

```
