### ISSUE TITLE
Can't open VS project

### ISSUE THREAD

**Issue by x2nie** [Embroidermodder/Embroidermodder#17]
I can't open the \Embroidermodder\project-files\visualstudio\libembroidery.sln
it seem created with MsVisual studio 2012

by just modifying 2 file (of that single VS solution), it doesnt work. Okay, finally it was opened in VS IDE, but there is no  any files found under the solution tree-explorer.
Maybe we need to create a new one from scratch. 
How?

**Comment by MsMathew** [comment]
Hi ,
I am trying to convert Visual Studio 2005 to 2012  and get the below errors.

Any one please help why is it not recognized - SQLLEN / ULEN ?

Thanks
Deepthi

Error	3	error C2061: syntax error : identifier 'SQLLEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	1927	1	
Error	4	error C2061: syntax error : identifier 'SQLULEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	1950	1	gle
Error	5	error C2061: syntax error : identifier 'SQLLEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	1959	1	gle
Error	6	error C2061: syntax error : identifier 'SQLULEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	2006	1	
Error	7	error C2061: syntax error : identifier 'SQLSETPOSIROW'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	2052	
Error	8	error C2061: syntax error : identifier 'SQLULEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h
