### ISSUE TITLE
Join the group on Open Collective Josh

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/Embroidermodder#264]
@JoshVarga I'm setting up donations, I may not even need to invite you because it used the GitHub organisation to set up the account.

**Comment by robin-swift** [comment]
We now have a " Show your support for Embroidermodder by sponsoring them. " widget at the bottom look!

**Comment by JoshVarga** [comment]
That's cool, how do we hand out donations to developers? I haven't worked with this portion before

**Comment by robin-swift** [comment]
So when we withdraw, the Open Collective group is our financial entity the corporate taxes and that are already paid. Our development time is an expense of that group. I'm not sure if we're still liable for personal income tax but we don't have to have a traditional company or charity this way.

For example, I'm a sole trader (I'm currently setting up a business as an artist, first filing will be April 2022) from the perspective of the UK, so I'll write this down as "freelance programming for the Embroidermodder group" and declare it as normal earnings.

Only me and you will have the power to release funds from this pot and it means there's no risk of money disappearing without a public budget showing where that money disappeared to.

We can in theory pay major contributors from this pot too. Similarly they are like consultants rather than employees.

I think it's about the safest approach. If we need to buy equipment or pay a regular contributor for their time, we can agree via email in advance then release the funds and label it appropriately.

**Comment by robin-swift** [comment]
The short version is: create and account and email me your username and I'll invite you. I asked a couple of mates to donate as a favour so we have a demo.

**Comment by robin-swift** [comment]
This is new to me too. I did some reading and the fact that Open Collective was supported by GitHub and they have some major groups based with them the Fiscal Host method seemed right. We're based in different countries for a start, so we'd need something like that anyway.
