### ISSUE TITLE
Scripting overhaul

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/Embroidermodder#266]
I think supporting scripting within Embroidermodder doesn't make sense.

1. All features that use scripting can be part of libembroidery instead.
2. Users who are capable of using scripting won't need it, they can alter their embroidery files in CSV format, or import pyembroidery to get access.
3. It makes maintaining the code a lot more complicated, especially if we move away from Qt.
4. Users who don't want the scripting feature will likely be confused by it, since we say that's what libembroidery, embroider and pyembroidery are for.

How about a simpler "call user shell" feature? Similar to texmaker we just call `system` on a batch or shell script supplied by the user and it processes the file directly then the software reloads the file. Then we aren't parsing it directly.

I don't want to change this without Josh's support because it's a fairly major change.

**Comment by TruGolfJV** [comment]
I totally agree.

I like the idea of scripting just so people that know how to code could write their own designs without needing to fully build the app. Scripting would be a very advanced feature that most users would be confused by. Libembroidery would be a good fit for advanced features.

**Comment by JoshVarga** [comment]
I totally agree.

I like the idea of scripting just so people that know how to code could write their own designs without needing to fully build the app. Scripting would be a very advanced feature that most users would be confused by. Libembroidery would be a good fit for advanced features.
