### ISSUE TITLE
install issues on macos 12.1

### ISSUE THREAD

**Issue by BartmanEH** [Embroidermodder/Embroidermodder#276]
here's what I've tried so far:
```
%git clone https://github.com/Embroidermodder/Embroidermodder
%cd Embroidermodder
%./build.sh --get-dependencies
%./build.sh
```
`./build.sh --get-dependencies` seems to run a `brew -update` which is annoying as I like to be careful with brew updates.
`./build.sh` failed with `./build.sh: line 105: cmake: command not found`
```
%brew install cmake
%./build.sh
```
this time it returned some warnings and this error:
```
CMake Error at CMakeLists.txt:184 (add_executable):
  Target "embroidermodder" links to target "Qt5::Widgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
not sure how to proceed

**Comment by robin-swift** [comment]
> `./build.sh --get-dependencies` seems to run a `brew -update` which is annoying as I like to be careful with brew updates.

Ah, okay, I'm not a Mac user so that's a useful criticism. I'll comment that out for now.

> `  Target "embroidermodder" links to target "Qt5::Widgets" but the target was`

I'm in the process of removing Qt5 from Embroidermodder (see #143), so the easy way forward is to wait until it will build without Qt5's Widgets library. Which I'd estimate is about 3 months from now.

What do you want Embroidermodder for in the mean time? There are other tools not in alpha like Embroidermodder 2 that I'd recommend, including our other project [`libembroidery`](https://github.com/Embroidermodder/libembroidery).

**Comment by robin-swift** [comment]
I just checked to comment out the update line, but [it's not present](https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh). Not sure why that's happening, maybe @JoshVarga knows better than me.

I'd recommend the line in place of `./build --get-dependencies`:

```
brew install qt5 qwt-qt5 pandoc
```

**Comment by BartmanEH** [comment]
Thanks for your attention! The main workflow I'm trying to accomplish is converting PES to SEW. Several freeware applications exist for Windows that can import/save SEW but not for mac. InkScape's Inkstitch Embroidery Extension is the main thing I use to generate the initial stitch file but it cannot export/save in SEW format. I'm looking for a quick way to take Inkstitch output in, say, PES format and convert it to SEW for the ancient machine I have access to.

**Comment by BartmanEH** [comment]
> I just checked to comment out the update line, but [it's not present](https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh). Not sure why that's happening, maybe @JoshVarga knows better than me.
> 
> I'd recommend the line in place of `./build --get-dependencies`:
> 
> ```
> brew install qt5 qwt-qt5 pandoc
> ```

maybe it's not running a full `brew update`:
```
Embroidermodder % ./build.sh --get-dependencies
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
```

**Comment by robin-swift** [comment]
Ah in that case, follow the build advice on the [`libembroidery`](https://github.com/Embroidermodder/libembroidery) to get our `embroider` command line tool. Then it's:

```
./embroider input.pes output.sew
```

If this doesn't work out the box then get back to me on that issues page, so I can close this one.

Cheers,
Robin
