### ISSUE TITLE
Does the full source to MobileViewer still exist?

### ISSUE THREAD

**Issue by JoshVarga** [Embroidermodder/Embroidermodder#278]

**Comment by robin-swift** [comment]
What's in the folder in here is what was in the repository that used to exist. I haven't changed it.

Although, the current plan is to merge the source code for the MobileViewers with the desktop version and have the application change layout depending on the device similar to how other desktop/tablet applications tend to share code.

SDL supports tablet interfaces and we can encode any differences in the YAML markup files.

Sorry it's a little hard to track at the moment, the design is still roughly the same, it's just I've been learning a lot about how to recreate it without having a massive UI library and without rebuilding from something as low level as FreeGLUT.

**Comment by robin-swift** [comment]
I'm making a few issues so it's easier to see where I'm at with the conversion.
