### ISSUE TITLE
Backup host

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/Embroidermodder#283]
I'm setting up https://github.com/Embroidermodder as the official mirror in case of any outages.

**Comment by robin-swift** [comment]
I've sent an invite to the embroidermodder gmail so it's not just me with the keys.

**Comment by robin-swift** [comment]
I'll close this issue when @JoshVarga has joined.

**Comment by JoshVarga** [comment]
Did you mean bitbucket?

**Comment by robin-swift** [comment]
> I'm setting up https://github.com/Embroidermodder as the official mirror in case of any outages.

Haha I just realised my error: https://gitlab.com/Embroidermodder

**Comment by JoshVarga** [comment]
I was confused until I got the email

**Comment by robin-swift** [comment]
Have you got access? Just so I can close this issue.
