### ISSUE TITLE
Static Window with action output and missing textures

### ISSUE THREAD

**Issue by habo** [Embroidermodder/Embroidermodder#290]
After compiling and installing on Debian 11 I can finally open an Embroiderymodder2 Window. But it seems static with strange Graphic and just action area output in Console.

Output after clicking on the copy Icon:
![image](https://user-images.githubusercontent.com/114314/193630675-a7629b50-294a-42d0-9b05-3abe8f0d5984.png)
Notice the Edit Menu is static and nothing besides the Console text changed at all.

Also there are texture failure messages:
```
habo@earth:~/.embroidermodder2$ ./embroidermodder 
Booting...
Failed to load texture.
assets/icons/save-as.png
Failed to load texture.
assets/icons/delete.png
Failed to load texture.
assets/icons/check-for-updates.png
Failed to load texture.
assets/icons/select-all.png
Failed to load texture.
assets/icons/design-details.png
Failed to load texture.
assets/icons/print-pattern.png
...
```

**Comment by robin-swift** [comment]
Hi @habo,

Yes, this is debug information that I am currently dealing with. The software is going through a ground-up rewrite to fix various issues with dependencies and distribution.

It's good to see that the render is consistent, I've literally just written that widget handler.

If you can describe your use case, I may be able to point you towards what you can do or tell you when it will be able to do that. For example, we have an underlying CLI called `embroider`.

Cheers,

Robin

**Comment by habo** [comment]
My usecase is just to have a better program than sophiesew. IC the debug for the action handler is the only thing working right now? I got the latest git update and now the list of missing icons is a lot shorter:
```
Booting...
Failed to load texture.
assets/icons/select-all.png
Failed to load texture.
assets/icons/changelog-dialog.png
Failed to load texture.
assets/icons/line-weight-selector.png
Failed to load texture.
assets/icons/treble-clef.png
 ```
If just found the embroider binary in build/extern/libembroidery/embroider and will test it next days. I guess this issue has been explained by yourself and is done
