### ISSUE TITLE
We lost the embroidermodder.org domain

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/Embroidermodder#292]
@JoshVarga I don't know who owns this but it looks like the subscription lapsed. Short term we can move it to the standard pages site embroidermodder.github.io so the documentation is still available.

**Comment by robin-swift** [comment]
https://embroidermodder.github.io/Embroidermodder is live, so that's solves half the problem.

**Comment by TruGolfJV** [comment]
I believe @redteam316 owned Embroidermodder.org. Maybe contact [@metal](https://github.com/Metallicow)

**Comment by robin-swift** [comment]
It seems like it's being squatted. I think calling it https://www.libembroidery.org is good enough. I'll close the issue.

**Comment by Metallicow** [comment]
The way I understood, it was that github hosted everything.
When I had contacted dns people we had a bit of a talk about why noone could manage to figure out what was done.
@JoshVarga has access to push commits to the website repo which reflects where everything is actually being hosted.
After Jon @redteam316 passed, I think one of the issues was getting where the donation was going changed. Josh changed some of that in a commit a while back. @robin-swift I'm not sure if github domain/websites ever expire... idunno

**Comment by robin-swift** [comment]
Well, we have a short term fix in that (as long as I'm around) I can pay for the https://www.libembroidery.org version of the site. `embroidermodder.org` is still being squatted, and I'll try to nab it back in a little under a year so legacy links go to the right place. I've just charged the domain name to our Open Collective page as a recurring expense (we have some redundancy there because Josh can change how expenses are submitted).

It's not quite true that GitHub hosts everything. We have the local version on GitHub that requests to `embroidermodder.org` got forwarded to something like `embroidermodder.github.io`. That forwarding step required us to buy the domain name through some third party like `godaddy.com`. Now the forwarding is done via `www.domains.google` meaning someone with access to my google account could fix it.

We could make this less fragile still but I think it's sufficient that if we're ever in the position of having to reclaim a domain name again, which is pretty much a case of "if I die", then my wife has agreed to respond to my emails to tie up loose ends left and would have access to my account on GitHub as well to discuss that with whoever is left on the project. Then the responsibility for the libembroidery.org domain could pass to Josh from her. In the worse event of both of us being unable to pass the reigns then just note that you'd have to claim it on the **10 October** in the following year to avoid the domain snipers.

The other check against fragility is replacing the embroidermodder.org links we can with libembroidery.org links so that people don't end up thinking that the project is over: it is emphatically not. I'll go change the Wikipedia one now.

Thanks for checking in,

Robin
