### ISSUE TITLE
Website/Email not working

### ISSUE THREAD

**Issue by marshallapparalautomation** [Embroidermodder/Embroidermodder#294]
Robin I tried reaching out to you via email. Send me the best contact info please. Also your domain seems to be down. Would be glad to assist.

**Comment by robin-swift** [comment]
Hi @marshallapparalautomation,

If you dig through #292 it's a long story but the short version is that the website is now: https://www.libembroidery.org (so, for example the wikipedia page now links to the new URL https://en.wikipedia.org/wiki/Embroidermodder ).

It appears Josh just sent me an access token to the embroidermodder gmail account so I'll see that processes, but generally I'd prefer using public forums like the Issues tab here.

Could you describe what you're interested in assisting with here? Then we can convert this issue into something more specific.

Cheers,

Robin

**Comment by robin-swift** [comment]
Ok, I got the email: I'll reply from my personal business email. It's more of a business question than a code one.

Closing as resolved.
