### ISSUE TITLE
Restore the old repo

### ISSUE THREAD

**Issue by Metallicow** [Embroidermodder/Embroidermodder#295]
@robin-swift 
I've had a thousand nightmares let alone users trying to build what Jon had created.
Essentially you destroyed all of that and all your endeavors with any code that existed. Including all the good ideas.
The worst thing you could do is delete someones history with no repercussions.

I am a developer too. I hate to make this hard, but what I have stated is what happened.
You need to restore the code that cannot be accessed by the people(the last commit before your actions as of taking over(over-writing the repo) ), or we have no other option than to fork Jon's last commit(and if if happens it will be set)(I'm sorry that you deleted someones college education, let alone 15+ years of it you just don't understand.)

The reason for this issue is that whoever was let into the organization(namely you) did not account for who was behind them nor who proceeded.
This is not a business and never will be. I can still fly a missile into your dot at any time. This is not a limp dick offer of what the rest of the world will do to you.
I'd prefer to like a life where people came to me and offered something other than my own AI back....

If you put the old repo back somewhere(by the same name), there probably wont be too many breaks.

"We just need you to restore what you destroyed"

Politely
,sincerely don't erase your history
    Edward Greig

**Comment by robin-swift** [comment]
@JoshVarga can you tell me what's going on here?

**Comment by robin-swift** [comment]
Fine, the history is as it was to (2013-2018) inclusive, I just grafted on my current work. You can disarm your missiles now.

**Comment by robin-swift** [comment]
That's a seperate issue, if you want to get into that can you open a new one.

**Comment by Metallicow** [comment]
Well GitHub apparently issued a robin broke the tree structure type of
message when you probably started changing thing. It didn't have a
timestamp. Maybe that is a new warning thing for those who have a fork and
someone at the trunk level actually deletes the repo. Git is unforgiving at
times, but back in the day all you really had was to blame whoever did it.
It was actually quite common thing, so when it spit out that message it
basically lead me back to an empty repo. It also is worded like a someone
might have done it intentionally. Apologies. But yes you need to treat the
repo code as if it was an actual dangerous machine. That is how gits tone
is when it pops out an error or such action or trigger.

**Comment by Metallicow** [comment]
@robin-swift I'd appreciate it if you made a link to the ol structure in the new documentation. Thank you. I do not have a lot of time to do things but it would be appreciated, especially by those 1000+ people I talked to in person. Disregard what negativity I meantioned about the website if you are mature enough,; just don't repeat it please. dot keys don't come cheep. If github falls tommorrow, then so be it....

If I had time, it would be like greased lightning. I appreciate all you are doing for the people. Keep up the bad work.
Thanks again.
-- Edward Greig

**Comment by robin-swift** [comment]
Sorry, I just saw this.

> I'd appreciate it if you made a link to the ol structure in the new documentation.

I'm not sure what the "ol structure" is, can you give me some references to what you mean? The website is actively changing because it's an output of Doxygen and I'm sorting out how that's generated at the moment.

**Comment by Metallicow** [comment]
This isn't the easiest thing to explain, but if you notice the organization
contains only 2 human beings. This was part of the design. So if you
theoretically link all of the members of the organization together, in a
sense you have successfully demonstrated that all machines work the same
way. When you compressed the code base, you sent the whole idea to another
address(which is possible for someone or something such as an AI to
modify). Anyone who has for example a git fetch/pull script will draw from
what you are doing now in this delta time. These folks are probably
interested in the c/c++ version because there is a problem with the memory
somewhere whether that be a human or a machine, and need to analyze which
one needs to do what. For example I see that you are interested in art...
You would want to use for example python/pascal/swift/etc... With the c/c++
bindings to be safe to generate the software on any operating system in the
world. You probably noticed a few empty CI repos and didn't realize that is
where the built exes end up somewhere down the line on some users machine
or computer or server. Basically add the link to the (now looks to be 5
archives) instead of source code in the open that could be compiled by a 10
year old with a simple I just want this to work script. Folks that are savy
enough to modify their script to fetch the code will now have to extract it
and check crcs ect...
On the other hand you also have to realize @Tatarize had ported the library
to python and it is now available on pypi which may not have been the best
idea. He is the type that is using it on a machine that is destructive and
realizes it doesn't have a "way back machine"(when you execute it the
material will be used). On the plus side he is correcting small hiccups
with the formats which would need ported back and also documenting the
machine at same time. On the negative side, I would never recommend anyone
use the python library with a program such as Krita(art), they would want
to use python scripting with compiled bindings. Krita is one of the few
programs that has an honest format that is open, so therefore common sense
should tell you that when function A goes to dot, it won't cut off some
poor kids arm. JavaScript is the type of script that will say I think this
is what you want, which is not always the case, hence why the bindings
existed. In this case JavaScript implementation is a command language and
not a script per say. Python is more powerful and if I tell JavaScript to
do it my way and it doesn't do it... Guess who the boss is.

Sorry again if some of this might seem a bit negative, but I could probably
put on a 3 hour talk and some folks still wouldn't understand the many
different ways to use a curve. Basically just a link to where the archives
are would be enough for now. Most people can copy paste a link from the
documentation into a fetch script on their own without much confusion.
Thanks

**Comment by robin-swift** [comment]
I feel like you're trying to cover a lot of issues in one message here. Can you seperate out and clearly state what you want me to do with respect to the documentation, please? It would also help if you supply a specific link like this: https://www.libembroidery.org/todo.html so I know where to fix it.

**Comment by Metallicow** [comment]
Well... As far as I can tell, the server or link is housed on GitHub
originally. So if a user executed a script that fetched the code, would end
up with your code, which would not be the right code. OK, let's say I have
a script that fetched your code and trys to compile it. You are the problem
in-between. A machine or musician knows that they CANNOT hit the same note
twice. Unless you are Robin or I need a detour. Try to click on what you
think will download the source code and then write a script. The only
difference will be the curve(link). I hope this makes sense. This is your
curve.

**Comment by Metallicow** [comment]
I will git on GitHub soon and post a link so you know. It is impossible to
do this from a phone.

**Comment by Metallicow** [comment]
@robin-swift
![embmodder2builderror](https://user-images.githubusercontent.com/4668356/232179591-ad4246ac-9af3-4641-9f78-a3143dce2590.jpg)
 It appears that it isn't here. Plus your "2.0 alpha" build for windows doesn't work out of the box.

Basically what we are needing is the "1.5 version" code(as some call it) from the organization timeline archived. The portion where the 'Experimental' directory was still there.
Here was my last merge on the timeline to give you a better idea of what the repo looked like before it got cut off. The c/c++ valgrind linux/windows/mac/rasperrypi version.
https://github.com/Metallicow/Embroidermodder

I have the actual working machines and the software Jon worked on and built and works and even other unreleased code, but what we just need is all that archived from the organization git history.

Basically the point right before you started modifying things(or more accurately before you became member #2/3). We need the archive we **know** will build on all platforms.
And of course after you create a backup(release page so its called now), there should be a link at like the end of the main readme file that states if folks are looking for that c/c++ version to direct them there to download the sourcecode archive from that point in time.

I am reluctant to do anything with the stuff I have forked at this time(such as push/pull/etc). It would be a big pain in the ass if I had to copy it all to another repo just to preserve the code you see has now disappeared... And I do NOT want to log into Jons github account after he is passed and upload it myself to his account handle, do you understand...?

**Comment by Metallicow** [comment]
In the immortal words of Jon "They will be more serious next time."
In the immortal words of Eddie "There will not be a next time."
Do you understand how delta time works? There is no way back machine.

**Comment by robin-swift** [comment]
Ok, I understand. You want the working build from about 190 commits ago to be available as a downloadable version and this experiment to not override it. Particularly that the release version should be available for "1.5".

What I'll do is create a branch with the current work on it as `imgui`, the master will be the only lightly modified Qt version to keep it working as new versions of Qt come out etc.

Thanks for making this clear for me: I'll work on this today.

**Comment by robin-swift** [comment]
Ok, so now `master` branch is the code as of 2018. The imgui development version is in the branch `imgui`.

I'll try and get CI to build the Qt version.

**Comment by Metallicow** [comment]
I think you understand, but this is not about QT or WX. This has to be wrong around our ways of thinking. x = x probably doesnt mean much to you. KABOOOM is what it means to me. We have to work together with curves to make them all work out.... 3 curves is PROBABLY a dangerous thing. or so say 12million

**Comment by robin-swift** [comment]
Well, in that case, I'll close this issue and make a new one about getting the releases to build for the `master` branch.

I do want to work with you on this, even if it's difficult for me to tell what you're saying. Please follow that new issue (#314).

**Comment by tatarize** [comment]
Meh, so long as the git hasn't be reverted or whatever, you should be able to create a tag or branch and leave it there.

**Comment by Metallicow** [comment]
it is hard to say python is 3 and c is 4 and parrot. pair it which what machine.....?
