### ISSUE TITLE
Not starting on windows

### ISSUE THREAD

**Issue by vajnaivik** [Embroidermodder/Embroidermodder#303]
Hi there!
I'd love to check the progress now and then, but I can't seem to get the program to run.
I've built with the following tools on a 64 bit win 10 machine:
- (mingw) x86_64-12.2.0-release-posix-seh-msvcrt-rt_v10-rev2
- cmake-3.26.0-rc3-windows-x86_64

During build I only see warnings, nothing seems to be obviously wrong.
Running embroidermodder.exe however gives no output at all and it simply does not start.
Am I missing something? Sorry if it's something obvious, I haven't used these build tools a lot.

**Comment by vajnaivik** [comment]
Just found out there is a build on github now.
The latest (19 feb.) version fails to start the same way.
Is there some dependency I need to run it?

**Comment by vajnaivik** [comment]
Tried on another machine with a relatively clean win 10, got the same results.

**Comment by vajnaivik** [comment]
Just found out there was an error report in the reliability monitor:
<details>
<summary>Error</summary>
Source
embroidermodder.exe

Summary
Stopped working

Date
‎2/‎19/‎2023 3:52 PM

Status
Report sent

Description
Faulting Application Path:	D:\dev\Embroidermodder\build\embroidermodder.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	embroidermodder.exe
Application Version:	0.0.0.0
Application Timestamp:	63f2366b
Fault Module Name:	libstdc++-6.dll
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	6393bd76
Exception Code:	40000015
Exception Offset:	0000000000022a46
OS Version:	10.0.19044.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	2168
Additional Information 2:	216812ada14a7a72bf194afe3de15c0a
Additional Information 3:	edb9
Additional Information 4:	edb969eac7443283299b7c432b9ce336

Extra information about the problem
Bucket ID:	d3427cb64a988731da5b3689bd4f60fd (1899171633081311485)
</details>

**Comment by robin-swift** [comment]
So this was currently a packaging error on my part: the assets directory wasn't copying right on windows.

If you either boot using `test.bat` or wait for the "daily" build I'm working on to update it should work.

Cheers,

Robin

**Comment by robin-swift** [comment]
This is fixed as of the current alpha build.

If you have any more problems, please open a new issue.
