### ISSUE TITLE
Embroidermodder builds now but does not run

### ISSUE THREAD

**Issue by bianchifan** [Embroidermodder/Embroidermodder#306]
when my last issue was closed I could build Embroidermodder on MInt20.3 and Ubuntu 22.10.
A simple Gui was offered, but not workable,I was not able to open a file.
No action possible, crash or "no action"
![Bildschirmfoto vom 2023-02-15 11-04-02](https://user-images.githubusercontent.com/17491743/220449797-0cf6d325-3df0-42b3-9cec-c6f23315b310.png)
![Bildschirmfoto vom 2023-02-15 11-04-47](https://user-images.githubusercontent.com/17491743/220450283-3b3ef222-169e-487e-ba61-b6282b3a5699.jpg)
![Bildschirmfoto vom 2023-02-15 11-11-46](https://user-images.githubusercontent.com/17491743/220450307-ebdb2520-5b20-4105-8144-456fefb88b2c.jpg)

Today evening I made a new pull and I see only a black window :((
And some ERRORS:
_Booting from "../assets/".
Reading Settings...
open ../assets/samples/embroidermodder_logo/conflicts/Embroidermodder.DST ../assets/samples/shamrockin/shamrockin.dst ../assets/samples/spiral/spiral5.csv ../assets/samples/spiral/spiral6.csv
ERROR: Failed to open file with name: ../assets/samples/embroidermodder_logo/conflicts/Embroidermodder.edr.
ERROR: Failed to open file with name: ../assets/samples/embroidermodder_logo/conflicts/Embroidermodder.rgb.
ERROR: Failed to open file with name: ../assets/samples/embroidermodder_logo/conflicts/Embroidermodder.col.
ERROR: Failed to open file with name: ../assets/samples/embroidermodder_logo/conflicts/Embroidermodder.inf.
numberOfColors: 2_

**Comment by robin-swift** [comment]
This may have been fixed by @JoshVarga's new path management, can you pull and try again?

**Comment by bianchifan** [comment]
I just did..4files were changed.
But the result i sstill the same :(
![Uploading Bildschirmfoto vom 2023-02-22 01-18-08.png…]()

**Comment by robin-swift** [comment]
Ok. This may take some guesswork. Try deleting your `build/settings.toml` and re-running.

**Comment by bianchifan** [comment]
No build/settings.toml...
Only settings_editor.toml in assets/ui

**Comment by robin-swift** [comment]
Huh. Ok, try:

```
rm -fr build
./test.sh
```

**Comment by bianchifan** [comment]
still the same...

and now I'm tired

**Comment by bianchifan** [comment]
BTW...
Today I noticed a first Alpha release :)
On Linux Mint 20.3 it does not run due to missing current GLIBC :(
On Ubuntu 22.10 it starts and it's possible to open existing designs.
One crash so far.
When I have some spare time I will fiddle out a little bit more.
Currently I can zoom in and out but I cannot pan..

![Bildschirmfoto vom 2023-02-22 12-43-38](https://user-images.githubusercontent.com/17491743/220655994-f58250d6-8071-4187-88bc-72a0453e9b8b.jpg)


![Bildschirmfoto vom 2023-02-22 12-43-08](https://user-images.githubusercontent.com/17491743/220656112-be9d6694-bc67-401a-aa67-e0bc62c88e85.jpg)

**Comment by robin-swift** [comment]
Great!

>  On Linux Mint 20.3 it does not run due to missing current GLIBC :(

This has it's own issue: #301 and it may be some time before I know what the minimum Linux Mint system requirement is.

>  Currently I can zoom in and out but I cannot pan..

Panning is fixed on the current HEAD, but I've yet to get that into the alpha pre-release.

`ERROR: action not in function_table.` is a long term problem I've made a new issue for (#307).

Missing color files I need a better solution for: but that's an issue for `libembroidery` (https://github.com/Embroidermodder/libembroidery/issues/215), not here.

Since we have #301, I'm closing this does not run as fixed.

Thanks for testing the alpha.
