### ISSUE TITLE
non-floating-point argument in call to function ‘_builtin_isnan’

### ISSUE THREAD

**Issue by bianchifan** [Embroidermodder/Embroidermodder#310]
Since I tested the alpha, I cannot build embroidermodder.
I waited one week or so and did several pulls, all with the same error.

_non-floating-point argument in call to function ‘__builtin_isnan’_

![Bildschirmfoto vom 2023-03-03 13-01-54](https://user-images.githubusercontent.com/17491743/222715577-03b2a2bd-1226-40c6-8124-b82cecd5fd40.png)

**Comment by robin-swift** [comment]
Ah, this is one of the those compiler-dependent errors: on mine it appears as a warning. I'll fix it in the next commit.

I'm about to hammer out a lot of these warnings so this will happen less often, but it'll take a while because I've got a few hundred to address.

**Comment by robin-swift** [comment]
The last commit should fix this, it has passed the build in GitHub Actions.

**Comment by bianchifan** [comment]
Hey, don't hurry!
I just wanted it to mention..
And yeah..it should be a warning ;)

**Comment by robin-swift** [comment]
I'll make a new issue for "clean up compiler warnings" and close this.
