### ISSUE TITLE
no Qt platform plugin could be initialized, Windows

### ISSUE THREAD

**Issue by vajnaivik** [Embroidermodder/Embroidermodder#315]
Hello there!
It looks like I'm getting a new crash starting the latest (2cd9b83) release on Windows 10.

I get the following popup on multiple machines when starting embroidermodder2.exe after unpacking:
![image](https://user-images.githubusercontent.com/61936589/233719544-c361fe92-16b5-4792-94fa-493abdf7c611.png)

Reliability monitor has some sort of a report again, hope it helps:
<details>
<summary>Error</summary>
Source
embroidermodder2.exe

Summary
Stopped working

Date
‎2023. ‎04. ‎21. 21:32

Status
Report sent

Description
Faulting Application Path:	C:\...\embroidermodder2\embroidermodder2.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	embroidermodder2.exe
Application Version:	0.0.0.0
Application Timestamp:	6442bc9a
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.19041.2788
Fault Module Timestamp:	62e593d6
Exception Code:	c0000602
Exception Offset:	0000000000117cd2
OS Version:	10.0.19044.2.0.0.256.48
Locale ID:	1038
Additional Information 1:	41ca
Additional Information 2:	41ca636f36f257d376273eee2f91b811
Additional Information 3:	0193
Additional Information 4:	0193f0eae787f63c54a1c05748ad9b9e

Extra information about the problem
Bucket ID:	d414dae8f2ead6dfcc3667c84e6e1abb (2032926391811316411)
</details>

**Comment by robin-swift** [comment]
There were some missing dlls, which I've now caught: try the current latest build.

Thanks for reporting this.

Robin
