### ISSUE TITLE
Converting CSV to DST, color layers are in reverse order

### ISSUE THREAD

**Issue by hariedo** [Embroidermodder/Embroidermodder#46]
I was able to successfully convert a CSV file to a DST file, and make use of it on a Brother SE-400 machine.  Hooray!  However, I ran into a couple issues; this is one of them.

My design uses five thread colors, and the last COLOR/STITCH/STITCH/... sequence of stitches were the first ones performed by the machine.  The order of stitches within the sequence appears correctly, so it's not just reversing the whole set of instructions.  It's just using the last set first.  This can cause problems if you plan various later colors to hide the longer traveling threads in earlier colors.

(I tried to convert the same CSV file to a PES file, but the PES was not recognized by a Brother SE-400, and never appeared in the USB loading area.)

**Comment by JoshVarga** [comment]
I fixed this issue after finding it independently. Embroidermodder should now save the stitches in the proper order. Let me know if you still have any issues.
