### ISSUE TITLE
VIsual Studio 2012 Conversion VC++ - Errors in SQLText.h  SQLLEN, SQLULEN

### ISSUE THREAD

**Issue by MsMathew** [Embroidermodder/Embroidermodder#66]
Hi ,
I am trying to convert code developed using VC++ - Visual Studio 2005 to  2012 ( Express for windows desktop , newly installed )   and get the below errors.

Any one please help why is it not recognized - SQLLEN / ULEN ?

Thanks in advance for any help !!!

Ms Mathew 

Error	3	error C2061: syntax error : identifier 'SQLLEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	1927	1	
Error	4	error C2061: syntax error : identifier 'SQLULEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	1950	1	
Error	5	error C2061: syntax error : identifier 'SQLLEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	1959	1	
Error	6	error C2061: syntax error : identifier 'SQLULEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	2006	1	
Error	7	error C2061: syntax error : identifier 'SQLSETPOSIROW'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h	2052	
Error	8	error C2061: syntax error : identifier 'SQLULEN'	c:\program files (x86)\windows kits\8.0\include\um\sqlext.h

**Comment by redteam316** [comment]
Sorry, but to my knowledge, this has nothing to do with our current development code using Qt and there isn't enough information to determine what you are trying to do. I'm closing this issue.

**Comment by x2nie** [comment]
@MsMathew, I think you have problem with Unicode. Thats is, not the problem of the EmbroideryModder project it self. 
TO resolve it, try to translate another project (non EmbroideryModder) to your target (VC++ - Visual Studio 2005 to 2012).
If there success, you might have no problem with EmbroideryModder.
