### ISSUE TITLE
File seems to be missing . . .

### ISSUE THREAD

**Issue by abtaylr** [Embroidermodder/Embroidermodder#75]
The file 'libembroidery-main.c' appears to be missing.  My attempt to compile failed.  I did a search of the downloaded files and then SourceForge and found nothing.

**Comment by redteam316** [comment]
What are you trying to compile, everything or just the library? You are correct that the file does not exist( or you may have typed it wrong ). Please provide the OS, compiler and the actual output stating where it is failing.
