### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dpquigl2** [Embroidermodder/Embroidermodder#83]
Is there a TODO list for work that can be done on the project other than the issues listed on github?

**Comment by JoshVarga** [comment]
David,

We do have a very high level, nearly road map level list of issues to
complete. You can find it in the source code at
https://github.com/Embroidermodder/Embroidermodder/blob/master/project-files/TODO


Thanks,
Josh Varga

**Comment by dpquigl** [comment]
Awesome. I seem to have put this issue in on my work github account instead of mine so I'll be responding and looking into things from my personal account instead.

**Comment by Metallicow** [comment]
@JoshVarga 
@dpquigl2 @dpquigl 
Remember quigley, you are being personal here, and any comments are reflecting your competition and are collated here by robots like ones we have set in motion(In the printshop?.?.?...). We have put your goal into a database that we will use to the projects own advantage as that is your will.
- Thanks much much much greatly

P.S.

    There is a TODO.ext list in the source code and it mentions pest control.

Thanks, Very much much much thanks again.

    - Embroidermodder Team
