### ISSUE TITLE
Wrong comment type on libembroidery/format-jef.c

### ISSUE THREAD

**Issue by gcarreno** [Embroidermodder/Embroidermodder#92]
Hi there,
Just tried to compile this on an Ubuntu 16.04 64b, gcc 5.4.0, g++ 5.4.0 and got this error:
```../libembroidery/format-jef.c:159:17: error: C++ style comments are not allowed in ISO C90```

Two solutions:
* Change the ```//``` to ```/* */```
* Add ```-std=c99``` to the compiler flags for that file.

Cheers,
Gus

**Comment by JoshVarga** [comment]
Gus,

Thanks for finding that, I made the required changes to the format-jef.c file and committed to Github.

Thanks,
Josh

**Comment by gcarreno** [comment]
Hey Josh,

Quite welcome and happy to help.

Cheers,
Gus
